# Generated by Django 2.2.2 on 2019-06-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='NewsImages', verbose_name='Изображение новости'),
        ),
    ]
