# Generated by Django 2.2.2 on 2019-06-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_newsmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='data',
            new_name='date',
        ),
    ]
