# Generated by Django 2.2.2 on 2019-06-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20190608_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['-date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
